server:
  port: 8090
  http2:
    enabled: true

spring:
  application:
    name: notification-service
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    default-property-inclusion: NON_NULL
  webflux:
    base-path: /api/notification
  data:
    mongodb:
      host: localhost
      port: 27017
      database: notification-service

camel:
  component:
    twilio:
      account-sid:
      enabled:
      password:
      username:
events:
  channels:
    EMAIL:
      endpoint: endpoint
      configuration:
        contentType: "text/html"
        from: from
        mail_smtp_auth: true
        mail_smtp_ssl_enable: true
        mail_smtp_starttls_enable: true
    API:
      endpoint:
      configuration:
        contentType: "text/html"







